### ISSUE TITLE
How to add more sources?

### ISSUE THREAD

**Issue by pbz134** [defgsus/teletext-viewer#1]
Hello,

I discovered a website that has a lot more teletext from various different channels. Is there anyway you (or I) could crawl them and integrate them into the viewer?

Here is the link:
https://som-teletextviewer.sim-technik.de/tius/teletextviewer/desk.php?pagnr=99_01&trynext=-1&ttx_select=p7de

**Comment by defgsus** [comment]
Hi @pbz134 ,
i have seen this site in the past. I think it's used in an iframe by SevenOne Entertainment (former address was here https://www.sevenonemedia.de/tv/portfolio/teletext/teletext-viewer but they now require a login). It contains ALL channels from the Pro7/Sat1 media empire.

There are two problems.
1. All pages are delivered as images. You need to OCR them to be able to store the content in a machine-friendly way.
2. Adding 30 more channels will make the scraping repositories (like [teletext-archive-2024](https://github.com/defgsus/teletext-archive-2024)) very big and eventually github might stop me from misusing the space. I try to stay below the 1GB margin that is noted in the docs at various places.

There is a cool dude who also collects those teletexts and stores them in the web archive. check out this discussion: https://github.com/defgsus/teletext-archive-2023/issues/1

**Comment by pbz134** [comment]
Danke für die Links, vielleicht kann man damit ja was anfangen!

Wenn man den Teletext als Bild speichert, ginge das doch praktisch auch, oder? Es sei denn, es nur als Bild zu haben hätte irgendeinen großen Nachteil.

Die Repos zum scrapen könntest du entweder (wie es derjenige vorgeschlagen hat) auf archive.org hochladen, oder weiter unterteilen. Leider hab ich keine Ahnung, wie man das alles selber macht, daher muss ich auf dich zählen :p

Allerdings hab ich es eben hinbekommen, die Bilder meiner verlinkten Webseite einfach mit WinHTTrack rauszuholen. Also die hätten wir schonmal zum arbeiten.

**Comment by defgsus** [comment]
Also.... Bilder sind erstmal viel größer als der Text der drin steht. Es ist aber nicht nur Platzverschwendung, es lässt sich sonst auch nicht mehr durchsuchen, was mir persönlich wichtig ist. Man kann die Bilder wahrsch. recht einfach in Text umwandeln aber das muss auch erstmal implementiert werden. 

@Casandro hat in seinen Archiven die ganzen 7/1 Sender mit drin, allerdings sind die im original t42 format, was auch *nicht ganz so einfach* zu parsen ist. Wir hatten kurz drüber geredet, dass man einen live-viewer in die archive hinbekommen könnte, wenn die daten nicht pro jahr zusammen-gezippt werden (Sonst müsste der browser jedesmal 2GB laden bevor er überhaupt was anzeigen kann).

Aber, kurz gesagt, es ist grad nicht meine Baustelle. Wünsche Dir viel Glück.

**Comment by pbz134** [comment]
Alles klar, danke dir
